#!/bin/bash

file_name="$1"

want_to_print=$(python3 "$file_name")

if [[ $want_to_print == "to-print" ]]; then
  pandoc -V documentclass=extarticle -V fontsize=17pt -V pagestyle=empty -V geometry:margin=1cm -V mainfont="DejaVu Sans" \
    'recipes.md' --pdf-engine=xelatex -o 'recipes.pdf'
  # xdg-open recipes.pdf
fi
